'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetUserClaims
    Public Property Id As Integer
    Public Property UserId As String
    Public Property ClaimType As String
    Public Property ClaimValue As String

    Public Overridable Property AspNetUsers As AspNetUsers

End Class
