'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetRoles
    Public Property Id As String
    Public Property Name As String

    Public Overridable Property AspNetUsers As ICollection(Of AspNetUsers) = New HashSet(Of AspNetUsers)

End Class
